version: "3.9"
services: 
  main:
    container_name: Longhorn
    network_mode: host
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - redis 
      - initcontainer
  redis:
    container_name: Redis
    network_mode: host
    image: redis:alpine
    ports: 
    - "6379:6379" 
  proxy: 
    container_name: NginxRevProxy
    network_mode: host
    image: nginx:alpine 
    ports: 
    - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/sites-available
    depends_on: 
      - main
  initcontainer: 
    container_name: InitContainer
    network_mode: host
    build: ./initContainer 
    depends_on: 
      - redis 


