name: Longhorn Main Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install flake8 pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: sudo docker build . --file Dockerfile --tag longhornprod:latest  
    - name: Stop Docker Container
      run: sudo docker stop Longhorn
    - name: Remove Docker Container
      run: sudo docker rm Longhorn 
    - name: Regenerate Docker Container
      run: sudo docker run -p 5000:5000 -d --name=Longhorn longhornprod:latest
    
     
